### ISSUE TITLE
Total in meta with pagination

### ISSUE THREAD

**Issue by rafaltrojanowski** [stas/jsonapi.rb#23]
## Expected Behavior
I'm calling 
http://{{host}}/api/tasks?page[size]=10

I would expect that `meta["total"]` equals the number of items passed to `jsonapi_paginate` method.

## Actual Behavior
```
    "meta": {
        "pagination": {
            "current": 1,
            "next": 2,
            "last": 20
        },
        "total": 10
    },
```

However `Model.all` size that I'm passing to `jsonapi_paginate` is different that total from meta.
Is it expected behaviour?

## Specifications

  - Version: 1.5.7
  - Ruby version: 2.7.1

**Comment by stas** [comment]
@rafaltrojanowski, thanks for reporting this!

Could you share your implementation, `total` by default is not provided in the meta, so that's something that was added on top.

The [pagination tests cover](https://github.com/stas/jsonapi.rb/blob/master/spec/pagination_spec.rb) a bunch of use-cases and there's also a separate conversation about adding total to meta #21 

Let me know if this helps :bow:

**Comment by rafaltrojanowski** [comment]
Thanks for your hints. The link to the conversation was especially helpful.
